### ISSUE TITLE
Time delay between X-ray and optical lasers

### ISSUE THREAD

**Issue by egaltier** [pcdshub/mec#7]
**Feature Request**

Define functions to delay the X-ray pulse vs an optical laser before interacting with a sample.

**Existing Alternatives**

I did not find any similar functions in the current mecpython version. The alternative is set several DG645 boxe's channels or VITARA target time manually, everytime that a different time is required. Incorrect values can be potentially set which could be detrimental to the laser systems (the VITARA could go out of range and pose issues for locking, bucket could be jumped for long pulse laser sysems, ...).

**Context**

While this request is linked to MEC, some of the functions are relevant for short pulse duration laser systems available in the other hutches. At MEC, we have a long pulse laser system whose delay vs the LCLS is achieved by changing delays on channels of an SRS box, and a short pulse laser system whose delay vs the LCLS is achieved by changing the target time of the VITARA. Changing timing in these devices is risky so controlling it by the use of a script helps to secure safe operation by the staff or the users. In the past, similar type of functions have been developed (old versions as `*.py` files are attached to this issue) but are now missing in the new hutch python implementation.

**Suggestions**
There should be two types of function implemented, as a function of the laser system in use:
```
> xray_delay_vs_spl
> xray_delay_vs_lpl
```
where `spl` stands for **short pulse laser** (a short pulse duration is ps or fs) and `lpl`stands for **long pulse laser** (a long pulse duration is ns). From the user perspective, it makes more sense to start naming these functions by `xray_delay` since in a pump-probe experiment at an FEL, the FEL is usually used as a probe with the optical laser used to excite the sample (whether it is used in bio, condensed material or high energy density science). Of course, we know that the X-ray arrival time on sample cannot be changed and that we actually change the optical laser timing. But in a python implementation, this should be transparent to users to avoid confusion.

Each function should have a set of common attribute like:
```
> xray_delay_vs_spl.get_delay() or xray_delay_vs_spl.status()
> xray_delay_vs_spl.set_t0()
> xrat_delay_vs_spl.mvr()
```
Each of these attributes are important for the operation, here are their description and common use:
```
def get_delay(self, verbose=False):
     ```
     For the short pulse laser (xray_delay_vs_spl), print the current delay like:
     > X-rays are delayed by 300 fs with respect to the short pulse laser
     If verbose is True, display more information concerning the actual value of the VITARA target time.
     For the short pulse laser (xray_delay_vs_lpl), print the current delay like:
     > X-rays are delayed by 5 ns from the long pulse laser
     If verbose is True, display more information concerning the actual values of the channels in the SRS box.
     Additionally, if a delay is `positive`, it means that the X-rays arrive **after** the optical laser, while when the
 delay is `negative` the X-rays arrive **before** the optical laser. So, if one entered `xray_delay_vs_spl(300e-15)`, the delay text could read:
     > X-rays arrive 300 fs after the short pulse laser.
     while, if `xray_delay_vs_spl(-300e-15)`, the delay text could read:
     > X-rays arrive 300 fs before the short pulse laser.
     The **after** and **before** could have a bold type of some specific colors as a plus.
     ```
     code

def set_t0(self, val):
     ```
     Extract the current values of the VITARA target time or the various relevant channels in the SRS box or use 
the **absolute** value and use it/them as a relative time overlap (`t0`) between the X-rays and the optical laser.
 The values could be stored in a PV or whatever makes sense to allow for easy access later. On the VITARA 
output example attached to this issue, the target value is pushed to 1020.57020 ns:
     > xray_delay_vs_spl.set_t0(1020.57020e-9) # or
     > xray_delay_vs_spl.set_t0()
     ```
     code

def mvr(self):
     ```
     Change the delay **relatively** vs the current delay. The current delay could be `t0` or any other delay. The 
value can be positive or negative, with units in `seconds` so that probing 100 fs later than the current delay 
value would be:
     > xray_delay_vs_spl.mvr(100e-15) # this would remove 100fs to the VITARA target time
     > xray_delay_vs_npl.mvr(10e-9) # this would remove 10e-9 to a specific channel in a SRS box
     > xray_delay_vs_npl.mvr(-2e-9) # this would add 2e-9 to a specific channel in a SRS box
     ```
     code

def xray_delay_vs_spl(self, val):
     ```
     Change the delay between the X-ray and the optical laser, setting the actual experimental value rather than 
the electronic value. It does change the delay vs the `t0` set earlier. Essentially, it would 'push' the `t0` - `val` 
directly to a channel/target field. The value can be positive or negative, with units in `seconds`. On the VITARA 
example attached to the issue, if a user wants to send the X-rays 300 fs later vs the optical laser, the command
 would read:
     > xray_delay_vs_spl(300e-15) # the value pushed to the VITARA would be 1020.57020e-9 - 300e-15 = 
1020.56990e-9, which will effectively trigger the optica laser 300 fs before the X-rays.
     ```
     code
``` 

**MEC Implementation**
The various relevant parameters for MEC are the following:
- for the lpl: the SRS DG box MEC:LAS:DDG:03, channel A, C, E and G needs to be changed. So, for example, if 
the values shown in the file `dg_lpl.png` are the `t0`for the lpl, then using `xray_delay_vs_lpl.set_t0()` would store the values:
  - `0.000875848` (chA), 
  - `0.0000689354` (chC),
  - `0.0000689354` (chE),
  - `0.00010184933` (chG)
Then, using `xray_delay_vs_lpl.get_delay()` would produce something like:
  - `> X-rays are delayed by 0 ns from the long pulse laser`
And if the users want to probe with the X-ray 3.0 ns later than the optical laser, using `xray_delay_vs_lpl(3.0e-9)` would set the values of the SRS DG box MEC:LAS:DDG:03 to:
  - `0.000875845` (chA), 
  - `0.0000689324` (chC),
  - `0.0000689324` (chE),
  - `0.00010184633` (chG)
Finally, using `xray_delay_vs_lpl.get_delay()` would produce something like:
  - `> X-rays are delayed by 3.0 ns from the long pulse laser` #or
  - `> X-rays arrive 3.0 ns after the long pulse laser`
- for the spl: the VITARA (LAS:FS6:VIT) target channel is the only value to change. Using `xray_delay_vs_spl.set_t0()` would store `1020.57020e-9` in a PV or something like that. Then, using `xray_delay_vs_lpl.get_delay()` would produce something like:
  - `> X-rays are delayed by 0 fs from the short pulse laser`
And if the users want to probe with the X-ray 500.0 fs later than the optical laser, using `xray_delay_vs_spl(500.0e-15)` would set the target value of the VITARA (LAS:FS6:VIT) to `1020.569700e-9 ` and `xray_delay_vs_spl.get_delay()` would produce something like:
  - `> X-rays are delayed by 500.0 fs from the short pulse laser` #or
  - `> X-rays arrive 500.0 fs after the short pulse laser`.

<img width="1440" alt="dg_lpl" src="https://user-images.githubusercontent.com/44449282/92986070-12aa8880-f46d-11ea-900a-7f9832ae05b1.png">
<img width="1119" alt="vitara" src="https://user-images.githubusercontent.com/44449282/92986073-163e0f80-f46d-11ea-8562-00e5cc15a181.png">

**Comment by egaltier** [comment]
It looks good! Just a note: for the LPL, `t0` will be set by each 4 channels, not just one. If at least one value is different than the saved `t0` while the others are correct then something is wrong and needs to be notified since these values control the amplification of the laser beam.

**Comment by slactjohnson** [comment]
@egaltier Yes, in the higher level version for the LPL we will loop over all 4 channels, applying the same relative delay to each. 

e.g. something like:

```
class NSTiming(object):
    channels = [TimingChannel(...),
               TimingChannel(...),
               ....]

    def set_t0(self, val):
        for channel in channels:
            channel.set_t0(val)
```

It sounds like you want to have some level of checking as well? I'm not sure how we can make sure that someone has not modified the PV Notepad values outside of this class, since the code is using this as our source of truth. The code doesn't save t0 values within the class; that's what the PVs are for.

**Comment by egaltier** [comment]
These 4 channel values are controlled by the laser people and essentially, should always be our `t0`. While they do not care about the 'absolute' EVR trigger input value, the whole laser is slaved to it and its perfomrance depends on it. SO I would suggest that the current values are saved as 4 laser PVs (maybe with a function called `lpl_save_master_timing()` or something like that. This would basically be a backup of the timing in case somebody change is inadvertantly using the commands we use for the timing. This is a precaution I think we need since this time we don't have a single channel to change the whole timing from but rather 4 channels slaved to the EVR itself. Then, out time delay functions would act on the channels, and essentially, the `save_t0` function is likely going to be a copy of the `lpl_save_master_timing()` but pushing the values onto a different set of 4 PVs. Again, these are redundant but is important for the safety of the laser. I'm pretty sure that at some point, we would like to have this `lpl_save_master_timing()` function changed into `lpl_save_timing()` to actually save all the channels of all the SRS boxes used to create the laser so you have a backup of these important timing functions in a place you can easily recall. For now, they save the status of the boxes on memory channels of the SRS box themselves (but if the boxes changed, these values are lost) and on a paper kept in a google drive folder.

**Comment by slactjohnson** [comment]
I agree, these values should be saved separately. In fact, while I was writing this code, it occurred to me that this functionality should actually be in an IOC because it would provide the redundancy that you want, as well as put everything in the archiver so you could recover from mistakes. However, I think that is a different development effort, and pen-and-paper (analog or digital) methods should be OK for now, since they have been working for years. :)

P.S.: I guess another alternative would be to just use up another 4 notepad PVs, and write a quick function to do this. I was planning on use MEC:NOTE:DOUBLE:41 through MEC:NOTE:DOUBLE:44 for saving the LPL channels; I could extend this to go through MEC:NOTE:DOUBLE:48 to have a second "backup" set. This backup set would only be affected by this lpl_save_master_timing() function (or somebody manually accessing the PV, but I can't do much about that, unless we have a separate IOC *hint* *hint*). :) 

What do you think?

**Comment by egaltier** [comment]
Getting 4 more PVs (up to `MEC:NOTE:DOUBLE:48`) seems good enough to start with, yes! As for the IOC, you decide what is the best way: if you think an IOC is the best way, go for it. I would have a meeting with Eric C. before to see what could be done on a more global approach.
